package org.gooru.insights.api.constants;

public class InsightsOperationConstants {

	public static final String ENTITY_ACTION_SEPARATOR = "~";
	
	public static final String ENTITY_INSIGHTS_COLLECTION = "Collection";
	
	public static final String ENTITY_INSIGHTS_RESOURCE = "Resource";
	
	public static final String ACTION_INSIGHTS_COLLECTION_VIEW = "View";
	
	public static final String ENTITY_INSIGHTS_CLASS = "Class";
	
	public static final String ENTITY_INSIGHTS_PROGRESS = "Progress";
	
	public static final String ENTITY_INSIGHTS_SUMMARY = "Summary";
	
	public static final String ENTITY_INSIGHTS_OE = "OpenEnded";
	
	public static final String ENTITY_INSIGHTS_REPORTS = "Report";
	
	public static final String ACTION_INSIGHTS_REPORTS = "Export";
	
	public static final String ACTION_INSIGHTS_VIEW = "View";
	
	public static final String ENTITY_INSIGHTS_SETTINGS ="Settings";
	
	public static final String ACTION_INSIGHTS_ADD = "Add";
	
	/**
	 * Collection Analytics
	 */
	public static final String OPERATION_COLLECTION_VIEW = ENTITY_INSIGHTS_COLLECTION + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_COLLECTION_VIEW;
	
	/**
	 * Exports
	 */
	public static final String OPERATION_INSIHGHTS_REPORTS = ENTITY_INSIGHTS_REPORTS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_REPORTS;
	
	public static final String OPERATION_INSIHGHTS_REPORTS_VIEWS = ENTITY_INSIGHTS_REPORTS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	/**
	 * Class Constants
	 */
	public static final String OPERATION_INSIHGHTS_CLASS_PROGRESS_VIEW = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ENTITY_INSIGHTS_PROGRESS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	public static final String OPERATION_INSIHGHTS_CLASS_SUMMARY_VIEW = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ENTITY_INSIGHTS_SUMMARY + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	public static final String OPERATION_INSIHGHTS_CLASS_OE_VIEW = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ENTITY_INSIGHTS_OE + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	public static final String OPERATION_INSIHGHTS_CLASS_COLLECTION_VIEW = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ENTITY_INSIGHTS_COLLECTION + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	public static final String OPERATION_INSIHGHTS_CLASS_RESOURCE_VIEW = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ENTITY_INSIGHTS_RESOURCE + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	public static final String OPERATION_INSIHGHTS_CLASS_EXPORTS = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ENTITY_INSIGHTS_REPORTS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_REPORTS;
	
	public static final String OPERATION_INSIHGHTS_CLASS_VIEW = ENTITY_INSIGHTS_CLASS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	
	/**
	 * add or view config settings
	 */
	public static final String OPERATION_INSIGHTS_CONFIG_SETTINGS_ADD = ENTITY_INSIGHTS_SETTINGS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_ADD;
	
	public static final String OPERATION_INSIGHTS_CONFIG_SETTINGS_VIEW = ENTITY_INSIGHTS_SETTINGS + ENTITY_ACTION_SEPARATOR + ACTION_INSIGHTS_VIEW;
	
	
	
	public static final String SIMPLE_TEXT = "simpleText";
	
	public static final String _ALL = "_all";
	
	public static final String MONITOR_JOBS = "monitoring_keys";
	
	public static final String CONSTANT_VALUE = "constant_value";

}
